### ISSUE TITLE
Add info icon modal

### ISSUE THREAD

**Issue by TimDaub** [emareg/classlesscss#11]
In a previous issue #8, I helped add tool tips as I had a problem with users not understanding my website.
A problem that was discussed in that issue, was that tool tips are essentially useless for any kind of touch-input device.

On my website, it turned out to be that way too. I doubt any user is really clicking on tooltips for more information.
But I kept on wondering what is the best UI modality that works both on desktop and mobile.

And then the other day it hit me when I was browsing another website. It's these ⓘ icons. And ideally, for mobile, they simply act as a button and e.g. open a modal.

<img width="836" alt="Screen Shot 2021-11-19 at 12 27 21" src="https://user-images.githubusercontent.com/2758453/142615423-45ab6e00-6696-4fb3-ae6d-65934bb72e36.png">

So a few questions to push this further:

- I doubt that there's a chance we can add this type of functionality without JS or can we?
- Could we just have the "i" icon and with a :hover tag that opens a tooltip?
- Are we generally interested in this element?
- From a HTML tag perspective, which tag would fit best?

**Comment by emareg** [comment]
I think this feature is already implemented?
On [classless.de](https://classless.de/), check the "Size" cell in the table under "2.1. Tables". [Here](https://github.com/emareg/classlesscss/blob/2b3072ee9a59e94295191f5dbb878b67755a1139/docs/index.html#L173) is the HTML and [here](https://github.com/emareg/classlesscss/blob/2b3072ee9a59e94295191f5dbb878b67755a1139/docs/classless.css#L202) the CSS. It works on desktop and mobile.

If this is not what you mean, what is missing in your opinion?

**Comment by TimDaub** [comment]
ah, looks great. I didn't know it was fully implemented. thanks
