### ISSUE TITLE
media query too wide on iphone 12 mini

### ISSUE THREAD

**Issue by davidthewatson** [emareg/classlesscss#14]
I have a site designed with classless.css and it's working smoothly in general. The one exception is that the moblie media queries seem too general to accommodate edge-case devices like the iphone 12 mini. In particular, the iphone 12 mini gets drop down menus in the nav no matter how narrow I make the single line content within the nav. I think this stems from these media queries:

    media (max-width: 40rem) {
	    nav ul:first-child > li:first-child:after { content: " \25BE"; }
	    nav ul:first-child > li:not(:first-child):not(.sticky) { display: none; }
	    nav ul:first-child:hover > li:not(:first-child):not(.sticky) { display: block; float: none !important; }
    }

being too wide for the iphone 12 mini.

So, if I understand correctly 40rem translates to 640px, meaning this media query gets invoked for the iphone 12 mini resulting in drop-down menus with the black down small triangle and such when the width of the content is actually well within the 360 px width of the iphone 12 mini, or 22.5rem.

https://www.webmobilefirst.com/en/devices/apple-iphone-12-mini/

This works for me:

    diff --git a/static/css/classless.css b/static/css/classless.css
    index a39d75f..bc51052 100644
    --- a/static/css/classless.css
    +++ b/static/css/classless.css
    @@ -235,7 +235,7 @@ nav ul > li > ul {
     }
     nav ul > li > ul > li { white-space: nowrap; }
     nav ul > li:hover > ul { display: block; }
    -@media (max-width: 40rem) {
    +@media (max-width: 22.5rem) {
            nav ul:first-child > li:first-child:after { content: " \25BE"; }
            nav ul:first-child > li:not(:first-child):not(.sticky) { display: none; }
            nav ul:first-child:hover > li:not(:first-child):not(.sticky) { display: block; float: none !important; }

Is the project open to pull requests around these issues? 

I likely don't have the design chops to get this right for every mobile device though the mini is an outlier - most devices seem huge by comparison. I'm not sure what the right answer is as there doesn't seem to be consensus on the wild variety of media queries to target this or similar devices. I just wanted to point out that this part of the mobile spectrum is not handled well by the existing media queries in classless.css, resulting in less usable design choices. An option to prefer desktop rendering would be an option here though I'm not sure what the right implementation is.

I can probably override this in my local styles.css but I ran into some trouble nullifying the media query above.

**Comment by davidthewatson** [comment]
I found that placing this media query in my local styles.css fixed the problem also without needing to modify classless.css:

    @media only screen and (-webkit-min-device-pixel-ratio: 3) {
	    nav ul:first-child > li:first-child:after { content: ""; }
	    nav ul:first-child > li:not(:first-child):not(.sticky) { display: inline-block; }
	    nav ul:first-child:hover > li:not(:first-child):not(.sticky) { display:inline-block; float:left !important; }
    }

That is, effectively reversing the original media query in classless.css, at least for iphone 12 mini. I'm not sure if there are other devices that might fall into this media query but it's a risk I'm willing to take without further guidance. I found a lot of the other media queries to be ineffective on this device - I turned the body background RED and used that to test.

**Comment by emareg** [comment]
Hi davidthewatson,
thanks for the info. However, I do not own an iPhone 12 Mini and I cannot reproduce the issue. When I test the responsiveness in Chrome for the "iPhone 12 Pro" dimensions it all looks fine. On a friend's iPhone (don't remember which), the page also appeared to be correct.

I have chosen `rem` as unit to base the media query roughly on the number of letters that fit in one line and so far this worked quite well. You could also try pixels and check if that helps. If the iPhone 12 Mini is the only device with issues then I would likely ignore it for now as you have found a workaround. I also think that there is no universal approach for all possible devices.
