### ISSUE TITLE
how to make it wider?

### ISSUE THREAD

**Issue by hiqsociety** [emareg/classlesscss#22]
why are most classless example look so thin?

how do i make it at least as wide as 58.com or something?

**Comment by HelloLudger** [comment]
Is this spam? The website you linked to is as wide as the image they are using to serve their comment...

You can create a theme and modify the --width-variable: https://classless.de/#sec-themes
Or you directly modify it in you classless.css at line 16:
https://github.com/emareg/classlesscss/blob/fc4405134d88516d189664d6cc1ac6b3a30fb4fe/docs/classless.css#L16

**Comment by emareg** [comment]
Thanks for answering :)
