### ISSUE TITLE
Padding on collapsed nav

### ISSUE THREAD

**Issue by flibustenet** [emareg/classlesscss#23]
Maybe padding should be reduced on small device where nav is on the left.
Something like:
```
@media (max-width:40rem) {
    nav ul:first-child > li {
        padding:0 0 0 0.6rem;
    }
}
```

**Comment by emareg** [comment]
A vertical padding of 0 looks too narrow for my taste but I will consider to use just `padding: .6rem;` globally. Thanks.

**Comment by flibustenet** [comment]
Maybe in a `var` as it depends on how many items we have in the menu (and it'll not break existing version) ?
