### ISSUE TITLE
Make grid and cards classless

### ISSUE THREAD

**Issue by HelloLudger** [emareg/classlesscss#5]
I find it odd to have to use classes for these functions. 
Maybe get some "inspiration" ;-) from https://github.com/vladocar/Basic.css, using sections seems logical to me.

**Comment by emareg** [comment]
I like the idea but I am not sure if this would feel intuitive. Besides there might be nested sections for other reasons and you should be able to opt out. I also saw a solution with custom tags but this would then be similar to using classes.
The advantage of the classes is that many people are used to it and the naming is quite consistent across libraries. Plus if you have any project that uses grid classes (e.g. with bootstrap) you can just copy the content and the basic layout works.

However, I think it would be nice to have a classless solution, let me know if you have further ideas.

**Comment by HelloLudger** [comment]
I prefer your way now :-)
