### ISSUE TITLE
sans-serif

### ISSUE THREAD

**Issue by vat9** [emareg/classlesscss#6]
¹: we import the font 'Open Sans' but if it fails, we fallback to Helvetica.

I’m seeing Arial as the fallback before sans-serif.  Is that because of sans-serif is Helvetica on some browsers but Arial is the default for many browsers?

**Comment by emareg** [comment]
I was testing whether Arial or Helvetica looks closer to Open Sans and Arial got accidentally into the commit. However, I think Helvetica is better so I will revert this change. If Helvetica is not installed then sans-serif will fall back to whatever installed font matches next, which might be Arial.
