### ISSUE TITLE
Make img tags scale without figure tag

### ISSUE THREAD

**Issue by TimDaub** [emareg/classlesscss#7]
I'm generating HTML from markdown. I've recently upgraded from an old version of classless and it now seems I need to wrap an image tag into a `<figure>` tag to make it scale correctly. I'd prefer to now interfere with how the markdown is rendered to HTML. For now, it just puts an `<img<` tag into the page. You can see the result here: https://rugpullindex.com/blog#March152021

I was able to fix the problem myself for now by adding the following as a global style `img { max-width: 100%}`.

**Comment by emareg** [comment]
Hi, yes this was on purpose. I also use classless for markdown generated content and I had several problems if every `<img>` tag is scaled to 100% as some figures are not meant to be to be scaled to full width. Maybe we can enable the 100% scaling if the `<img>` is the only child of a `<p>` tag.

**Comment by TimDaub** [comment]
> Maybe we can enable the 100% scaling if the `<img>` is the only child of a `<p>` tag.

I'm not sure. In the context of using classlessde for a variety of mark down compilers, we should understand if they will insert the `<img>` tag plainly into the document (e.g. without embedding it into a parent element like `<figure>` or `<p>`.).

In the end, the problem it comes down to is that as a markdown to HTML compiler user, I have no control over the HTML the markdown compiler is outputting. So IMO the most conservative approach towards scaling the `<img>` tag is what I'm interested in. Basically, that an `<img>` tag gets scaled without anything.



> I also use classless for markdown generated content and I had several problems if every `<img>` tag is scaled to 100% as some figures are not meant to be to be scaled to full width.

How about we make scaling to 100% the default and handle edge cases when its embedded in a parent tag like `<figure>`?

IMO, that'd make the whole concept semantically more correct too. An image in a document is "just there", whereas e.g. a figure in an `<article>` or in a `<p>` needs to comply to the rules of the parent element.
